export const ORGANIZATION_NAME = 'ASD Soccer Dream Fermana'
export const TEAM_NAME = 'Soccer Dream Fermana'
export const CONTACT_EMAIL = 'soccerdreamfermana@gmail.com'
export const CONTACT_PHONE = '+39 340 983 8158'
export const CONTACT_ADDRESS = 'Via Carpenette, 5 - 63844 Grottazzolina (FM)'
export const SIGNATURE_PROJECT_NAME = 'Il Tetto di un Sogno'
